import type { Metadata } from "next"
import "../globals.css"
import "./openclaw.css"

export const metadata: Metadata = {
  metadataBase: new URL("https://openclaw.omoios.dev"),
  title: "OpenClaw - Your AI Assistant That Handles Clients While You Sleep",
  description:
    "Stop answering the same WhatsApp questions 50 times a day. OpenClaw responds to leads, schedules consultations, and follows up automatically — so you can focus on closing deals. $49 setup.",
  keywords: [
    "OpenClaw",
    "AI assistant",
    "WhatsApp automation",
    "client intake automation",
    "lead qualification",
    "relocation consultant",
    "service business automation",
    "calendar booking bot",
    "automated follow-ups",
  ],
  openGraph: {
    type: "website",
    locale: "en_US",
    title: "OpenClaw - Your AI Assistant That Handles Clients While You Sleep",
    description:
      "Stop answering the same WhatsApp questions 50 times a day. OpenClaw responds to leads, schedules consultations, and follows up automatically. $49 one-time setup.",
    url: "https://openclaw.omoios.dev",
    siteName: "OpenClaw",
    // Image auto-generated by opengraph-image.tsx
  },
  twitter: {
    card: "summary_large_image",
    title: "OpenClaw - Your AI Assistant That Handles Clients While You Sleep",
    description:
      "Stop answering the same WhatsApp questions 50 times a day. OpenClaw responds to leads and schedules consultations automatically. $49 setup.",
    // Image auto-generated by opengraph-image.tsx
  },
  robots: {
    index: true,
    follow: true,
  },
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="font-sans">
        {children}
      </body>
    </html>
  )
}
