#!/bin/bash
# Setup test environment for OmoiOS
# Creates .env.test file and verifies configuration

set -e

echo "🔧 Setting up test environment..."

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# ============================================================================
# Step 1: Create .env.test
# ============================================================================

echo -e "${YELLOW}📝 Creating .env.test file...${NC}"

if [ -f .env.test ]; then
    echo -e "${YELLOW}⚠️  .env.test already exists. Backing up to .env.test.backup${NC}"
    cp .env.test .env.test.backup
fi

cat > .env.test << 'EOF'
# Test Environment Variables
# Auto-generated by scripts/setup_test_environment.sh

# Database (PostgreSQL test instance)
DATABASE_URL_TEST=postgresql+psycopg://postgres:postgres@localhost:15432/app_db

# Redis (test instance)
REDIS_URL_TEST=redis://localhost:16379/1

# LLM API (mock key for tests)
LLM_API_KEY=test-key-mock-not-a-real-key

# Fireworks AI (mock key)
FIREWORKS_API_KEY=test-fireworks-mock-key

# Auth secrets (test-only, not secure)
AUTH_JWT_SECRET_KEY=test-jwt-secret-key-not-for-production-12345678

# OpenAI (mock key for embedding tests)
OPENAI_API_KEY=test-openai-mock-key

# GitHub (mock token)
GITHUB_TOKEN=test-github-token-mock

# Supabase (optional, for Supabase integration tests)
# SUPABASE_URL=https://test.supabase.co
# SUPABASE_ANON_KEY=test-anon-key
# SUPABASE_SERVICE_ROLE_KEY=test-service-key

# Logfire (optional, for observability tests)
# LOGFIRE_TOKEN=test-logfire-token

# Environment identifier (CRITICAL)
OMOIOS_ENV=test
EOF

echo -e "${GREEN}✅ .env.test created${NC}"

# ============================================================================
# Step 2: Verify config/test.yaml exists
# ============================================================================

echo -e "${YELLOW}📋 Checking config/test.yaml...${NC}"

if [ ! -f config/test.yaml ]; then
    echo -e "${RED}❌ config/test.yaml not found!${NC}"
    echo -e "${YELLOW}Creating config/test.yaml...${NC}"
    
    mkdir -p config
    
    cat > config/test.yaml << 'EOF'
# Test environment configuration
# Fast intervals and disabled features for testing

monitoring:
  guardian_interval_seconds: 1
  conductor_interval_seconds: 2
  health_check_interval_seconds: 1
  auto_steering_enabled: false

task_queue:
  age_ceiling: 60
  sla_urgency_window: 10

worker:
  concurrency: 1
  heartbeat_interval_seconds: 1

features:
  enable_mcp_tools: false
  enable_github_sync: false
  enable_guardian: false

testing:
  strict_mode: true
  use_fakeredis: true
EOF
    
    echo -e "${GREEN}✅ config/test.yaml created${NC}"
else
    echo -e "${GREEN}✅ config/test.yaml exists${NC}"
fi

# ============================================================================
# Step 3: Verify .gitignore
# ============================================================================

echo -e "${YELLOW}🔒 Checking .gitignore...${NC}"

if ! grep -q ".env.test" .gitignore 2>/dev/null; then
    echo ".env.test" >> .gitignore
    echo -e "${GREEN}✅ Added .env.test to .gitignore${NC}"
else
    echo -e "${GREEN}✅ .env.test already in .gitignore${NC}"
fi

if ! grep -q ".testmondata" .gitignore 2>/dev/null; then
    echo ".testmondata" >> .gitignore
    echo -e "${GREEN}✅ Added .testmondata to .gitignore${NC}"
else
    echo -e "${GREEN}✅ .testmondata already in .gitignore${NC}"
fi

# ============================================================================
# Step 4: Install test dependencies
# ============================================================================

echo -e "${YELLOW}📦 Installing test dependencies...${NC}"

uv add --group test pytest-testmon pytest-xdist pytest-sugar pytest-timeout pytest-randomly

echo -e "${GREEN}✅ Test dependencies installed${NC}"

# ============================================================================
# Step 5: Verify database is running
# ============================================================================

echo -e "${YELLOW}🗄️  Checking PostgreSQL...${NC}"

if pg_isready -h localhost -p 15432 -U postgres >/dev/null 2>&1; then
    echo -e "${GREEN}✅ PostgreSQL is running on port 15432${NC}"
else
    echo -e "${YELLOW}⚠️  PostgreSQL not detected on port 15432${NC}"
    echo -e "   Start with: docker-compose up -d postgres"
fi

# ============================================================================
# Step 6: Verify Redis is running
# ============================================================================

echo -e "${YELLOW}📮 Checking Redis...${NC}"

if redis-cli -p 16379 ping >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Redis is running on port 16379${NC}"
else
    echo -e "${YELLOW}⚠️  Redis not detected on port 16379${NC}"
    echo -e "   Start with: docker-compose up -d redis"
fi

# ============================================================================
# Step 7: Run baseline test collection
# ============================================================================

echo -e "${YELLOW}🧪 Running baseline test collection...${NC}"

export OMOIOS_ENV=test

if uv run pytest --testmon --collect-only -q >/dev/null 2>&1; then
    echo -e "${GREEN}✅ Test collection successful${NC}"
else
    echo -e "${RED}❌ Test collection failed${NC}"
    echo -e "   Check pytest configuration and test files"
fi

# ============================================================================
# Summary
# ============================================================================

echo ""
echo -e "${GREEN}================================================${NC}"
echo -e "${GREEN}✅ Test Environment Setup Complete!${NC}"
echo -e "${GREEN}================================================${NC}"
echo ""
echo "Next steps:"
echo "  1. Run: make test          # Quick feedback with testmon"
echo "  2. Run: make test-unit     # Unit tests only"
echo "  3. Run: make test-all      # Full test suite"
echo "  4. Run: make test-coverage # Coverage report"
echo ""
echo "Configuration:"
echo "  - .env.test created (secrets & URLs)"
echo "  - config/test.yaml verified (app settings)"
echo "  - pytest-testmon installed"
echo "  - .gitignore updated"
echo ""
echo "Usage:"
echo "  make test          # Run only affected tests"
echo "  make test-help     # Show all test commands"
echo ""

