#!/usr/bin/env python3
# Idempotent local-smoke-account bootstrap.
#
# - Reads cached `.env.smoke-test.local` first.
# - Validates the cached API key with one GET /auth/me. If still good,
#   exits "already valid" instantly.
# - Otherwise, finds-or-creates each resource (user, org, key,
#   workspaces) instead of regenerating them.
# - Writes the resolved set back to `.env.smoke-test.local`.
#
#   uv run --with httpx --with psycopg --with passlib --with bcrypt \
#       python scripts/setup_local_smoke_account.py [--api http://localhost:18000]

from __future__ import annotations

import argparse
import secrets
import string
import sys
import time
from pathlib import Path

import httpx
import psycopg

REPO = Path(__file__).resolve().parent.parent
ENV_OUT = REPO / "backend" / ".env.smoke-test.local"
LOCAL_DSN = "host=localhost port=5432 dbname=omoi_os_dev user=kevinhill"


def _print(glyph: str, msg: str) -> None:
    color = {"✓": "\033[32m", "·": "\033[90m", "▸": "\033[36m", "✗": "\033[31m"}.get(
        glyph, ""
    )
    print(f"  {color}{glyph}\033[0m {msg}", flush=True)


def gen_password() -> str:
    upper = secrets.choice(string.ascii_uppercase)
    lower = secrets.choice(string.ascii_lowercase)
    digit = secrets.choice(string.digits)
    special = secrets.choice("!@#$%^&*")
    rest = "".join(
        secrets.choice(string.ascii_letters + string.digits + "!@#$%^&*")
        for _ in range(20)
    )
    chars = list(upper + lower + digit + special + rest)
    secrets.SystemRandom().shuffle(chars)
    return "".join(chars)


def load_cached() -> dict[str, str]:
    if not ENV_OUT.exists():
        return {}
    out: dict[str, str] = {}
    for line in ENV_OUT.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#") or "=" not in line:
            continue
        k, v = line.split("=", 1)
        out[k.strip()] = v.strip()
    return out


def write_env(out: dict[str, str]) -> None:
    keys = [
        "OMOIOS_API_BASE_URL",
        "OMOIOS_TEST_EMAIL",
        "OMOIOS_TEST_PASSWORD",
        "OMOIOS_PLATFORM_API_KEY",
        "OMOIOS_TEST_ORG_ID",
        "OMOIOS_TEST_WORKSPACE_A",
        "OMOIOS_TEST_WORKSPACE_B",
        "OMOIOS_USER_JWT",
    ]
    lines = ["# Auto-generated by setup_local_smoke_account.py — do not commit."]
    for k in keys:
        if k in out:
            lines.append(f"{k}={out[k]}")
    ENV_OUT.write_text("\n".join(lines) + "\n")


def validate_cached(api: str, api_key: str) -> bool:
    """One cheap call — if the cached api key still works, we're done."""
    try:
        with httpx.Client(base_url=api, timeout=5.0) as c:
            r = c.get("/api/v1/auth/me", headers={"Authorization": f"Bearer {api_key}"})
        return r.status_code == 200
    except Exception:
        return False


def db_reset_password(email: str, pw: str) -> bool:
    from passlib.hash import bcrypt

    with psycopg.connect(LOCAL_DSN) as conn, conn.cursor() as cur:
        cur.execute("SELECT 1 FROM users WHERE email = %s", (email,))
        if cur.fetchone() is None:
            return False
        cur.execute(
            "UPDATE users SET hashed_password = %s, is_verified = true, "
            "email_confirmed_at = NOW(), is_active = true WHERE email = %s",
            (bcrypt.hash(pw), email),
        )
        conn.commit()
        return True


def find_org_for_user(c: httpx.Client, jwt: str, name_prefix: str) -> str | None:
    """Find an existing org owned by the logged-in user matching name prefix."""
    r = c.get("/api/v1/organizations", headers={"Authorization": f"Bearer {jwt}"})
    if r.status_code != 200:
        return None
    items = r.json() if isinstance(r.json(), list) else r.json().get("items", [])
    for o in items:
        if (o.get("name") or "").startswith(name_prefix):
            return o["id"]
    return None


def find_or_mint_key(c: httpx.Client, jwt: str, org_id: str, name: str) -> str:
    """List api keys for org; if one with our name already active, mint a new
    one (keys can't be re-fetched). Otherwise mint fresh."""
    r = c.post(
        "/api/v1/auth/api-keys",
        headers={"Authorization": f"Bearer {jwt}"},
        json={"name": name, "scopes": ["*"], "organization_id": org_id},
    )
    if r.status_code in (200, 201):
        return r.json()["key"]
    sys.exit(f"api-key mint failed: {r.status_code} {r.text[:200]}")


def find_or_create_workspace(
    c: httpx.Client, jwt: str, org_id: str, name: str
) -> str:
    H = {"Authorization": f"Bearer {jwt}"}
    r = c.get("/api/v1/workspaces", headers=H)
    if r.status_code == 200:
        items = r.json() if isinstance(r.json(), list) else r.json().get("items", [])
        for ws in items:
            if ws.get("name") == name:
                return ws["id"]
    r = c.post(
        "/api/v1/workspaces",
        headers=H,
        json={"name": name, "slug": f"{name}-{int(time.time())}", "org_id": org_id},
    )
    if r.status_code not in (200, 201):
        sys.exit(f"workspace {name} failed: {r.status_code} {r.text[:200]}")
    return r.json()["id"]


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--api", default="http://localhost:18000")
    p.add_argument("--email", default="omoi-local-smoke@autoworkz.org")
    p.add_argument("--force", action="store_true", help="bypass cache validation")
    args = p.parse_args()

    api = args.api.rstrip("/")
    cached = load_cached()

    # ─── fast-path: cache still valid ──────────────────────────────────────
    if not args.force and cached.get("OMOIOS_PLATFORM_API_KEY"):
        t = time.perf_counter()
        if validate_cached(api, cached["OMOIOS_PLATFORM_API_KEY"]):
            ms = (time.perf_counter() - t) * 1000
            _print("✓", f"cache valid (validated in {ms:.0f}ms) — nothing to do")
            print(f"      {ENV_OUT}")
            return 0
        _print("·", "cache invalid, re-bootstrapping")

    out = dict(cached)
    out["OMOIOS_API_BASE_URL"] = api
    out["OMOIOS_TEST_EMAIL"] = args.email
    pw = out.get("OMOIOS_TEST_PASSWORD") or gen_password()

    # ─── user (find-or-create via DB) ──────────────────────────────────────
    t = time.perf_counter()
    if db_reset_password(args.email, pw):
        out["OMOIOS_TEST_PASSWORD"] = pw
        ms = (time.perf_counter() - t) * 1000
        _print("✓", f"user reset (DB direct, {ms:.0f}ms): {args.email}")
    else:
        with httpx.Client(base_url=api, timeout=10.0) as c:
            r = c.post(
                "/api/v1/auth/register",
                json={"email": args.email, "password": pw, "full_name": "Local Smoke"},
            )
            if r.status_code not in (200, 201):
                sys.exit(f"register failed: {r.status_code} {r.text[:300]}")
            out["OMOIOS_TEST_PASSWORD"] = pw
            db_reset_password(args.email, pw)  # ensure verified
            _print("✓", f"registered {args.email}")

    # ─── login → JWT ───────────────────────────────────────────────────────
    with httpx.Client(base_url=api, timeout=10.0) as c:
        t = time.perf_counter()
        r = c.post("/api/v1/auth/login", json={"email": args.email, "password": pw})
        if r.status_code != 200:
            sys.exit(f"login failed: {r.status_code} {r.text[:300]}")
        jwt = r.json()["access_token"]
        out["OMOIOS_USER_JWT"] = jwt
        _print("✓", f"logged in ({(time.perf_counter() - t) * 1000:.0f}ms)")

        # ─── org (reuse existing if present) ──────────────────────────────
        t = time.perf_counter()
        org_id = find_org_for_user(c, jwt, "Local Smoke")
        if org_id:
            _print("✓", f"reused org {org_id[:8]}…")
        else:
            slug = f"local-smoke-{int(time.time())}"
            r = c.post(
                "/api/v1/organizations",
                headers={"Authorization": f"Bearer {jwt}"},
                json={"name": "Local Smoke Org", "slug": slug},
            )
            if r.status_code not in (200, 201):
                sys.exit(f"org create failed: {r.status_code} {r.text[:300]}")
            org_id = r.json()["id"]
            _print("✓", f"new org {org_id[:8]}… slug={slug}")
        out["OMOIOS_TEST_ORG_ID"] = org_id

        # ─── api key (mint fresh — old keys are write-only) ────────────────
        t = time.perf_counter()
        api_key = find_or_mint_key(c, jwt, org_id, "local-smoke-platform")
        out["OMOIOS_PLATFORM_API_KEY"] = api_key
        _print(
            "✓",
            f"api-key minted ({api_key[:14]}…  in {(time.perf_counter() - t) * 1000:.0f}ms)",
        )

        # ─── workspaces (find-or-create) ───────────────────────────────────
        for label, name in (("OMOIOS_TEST_WORKSPACE_A", "smoke-a"),
                            ("OMOIOS_TEST_WORKSPACE_B", "smoke-b")):
            t = time.perf_counter()
            ws_id = find_or_create_workspace(c, jwt, org_id, name)
            out[label] = ws_id
            _print(
                "✓",
                f"workspace {name} {ws_id[:8]}…  in {(time.perf_counter() - t) * 1000:.0f}ms",
            )

    write_env(out)
    _print("✓", f"wrote {ENV_OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
